name: Getting Things Done Clear Job

on:
  schedule:
    - cron: "0 9 * * *"  # Executa todos os dias às 06:00 UTC
  workflow_dispatch:  # Permite rodar manualmente pelo GitHub Actions

jobs:
  clear-notion:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Notion clear
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python -c "import asyncio; from src.main import clear; asyncio.run(clear())"
